fading = false;
shadow = false;

# opacity-rule = [ "90:class_g = 'kitty'" ];

rules = (
    { match = "name = 'rofi - dmenu'"; blur-background = true; },
)

blur:
{
    method = "gaussian";
    size = 6;
    deviation = 5.0;
};

backend = "glx";
vsync = true;
use-damage = true;
