#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 0
bspc config window_gap 7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^1' follow=on
bspc rule -a firefox desktop='^2' follow=on

THEME=$(cat ~/.theme)

# Status bar.
~/.config/polybar/launch.sh $THEME &

# Background image.
feh --bg-scale ~/.config/bspwm/assets/$THEME.png

# Composite manager.
picom -b --experimental-backend
